# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=rachitha123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=finance-backend
server.port=8080

# JWT Secret (keep this secret!)
app.jwt.secret=mySecretKey123456789012345678901234567890
app.jwt.expiration=86400000

spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false